OnlineMarket/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from Graduation import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.search),
    url(r'^select-item/$', views.select),
    # url(r'^Post-item/$', views.PostItem),
     url(r'^product/$', views.test1),
    # url(r'^test2/$', views.test),
    url(r'^my-products/$', views.myProduct),
    url(r'^products/user/(?P<userId>[0-9]+)$',views.productsDetalis ),
    url(r'^update/user/(?P<id>[0-9]+)$', views.update),
    url(r'^inbox/$', views.inbox),
    url(r'^filtering/$', views.filteringCamera),
    url(r'^devices/$', views.filteringele),
    url(r'^Accessories/$', views.filterinAccessories),
    url(r'^scholarship/$', views.filterinscholarship),
    url(r'^notfound/$', views.notfound),

    url(r'^Books/$', views.filterinbooks),


    url(r'^test3/$', views.RecommendtionData),



    # url('test2/', include('social.apps.django_app.urls', namespace='social12')),
    # url('test2/', include('django.contrib.auth.urls', namespace='auth12')),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url('', include('django.contrib.auth.urls', namespace='auth'))

]

OnlineMarket/forms.py
from django import forms




class search_text(forms.Form):
    search = forms.CharField(max_length=1500)
#In order to select what we want to post
class Radio_select(forms.Form):
    CHOICES=[('select1','Post a job '),
         ('select2','Post an item to sell,')]

    select = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

#
class Post_item(forms.Form):


    CHOICES2=[('Electronic Devices', 'Electronic Devices'),
               ('Scholarship', 'Scholarship')
               ,('Books','Books'),
              ('Home staff','Home staff'),('Other','Other')]


    ItemName=forms.CharField(max_length=50)
    ItemType=forms.ChoiceField(choices=CHOICES2,required=True)
    ItemPrice=forms.FloatField()
    ItemDescrption=forms.CharField(max_length=100)

class Status(forms.Form):
    CHOICES = [('New','New'),
                ('Second Hand','Second Hand')]

    ItemStatus=forms.ChoiceField(choices=CHOICES,required=True)



class Post_item1(forms.Form):
    CHOICES3 = [('0 ', ' '),
        ('Computer', 'Computer'),
                ('Smart Phone', 'Smart Phone')
        , ('Tablet', 'Tablet'),
                ('Camera', 'Camera'), ('Accessories', 'Accessories')]
    # ItemName=forms.CharField(max_length=50)
    ItemSubType = forms.ChoiceField(choices=CHOICES3, required=True)

class MainImage(forms.Form):
    Image1 = forms.FileField()
class secondImage(forms.Form):
    Image2 = forms.FileField()
class thirdImage(forms.Form):
    Image3 = forms.FileField()

class DeleteImage1(forms.Form):
    delete1 = forms.BooleanField()
class DeleteImage2(forms.Form):
    delete2 = forms.BooleanField()

class DeleteImage3(forms.Form):
    delete3 = forms.BooleanField()

class sendmessage(forms.Form):
    sendMessage = forms.CharField(max_length=1500)

templates/bootstrap-shop/inbox.html
{% load static %}
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
      <style>
.entTXT{
{#    position: absolute;#}
    bottom:0px;
    width: 100%;
    height:70px;
    padding: 12px 12px;
    margin: 18px 0;
    display: block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
</style>
      <style>
.send{
    float: right;
    font-size: 12px;
    font-weight:bold;
    width: 25%;
    height:15px;
    background-color: deepskyblue;
    color: white;
    padding: 25px 15px;
    margin: 4px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}
      </style>

        <style>
      .people
            {
                   left:0;
                   right:0;
                   top:60px;
                   padding:2px;
                 height: 500px;
                overflow-y: scroll;
                overflow-x: hidden;
            }
      </style>
      <style>
      .right

            {    left:0;
               right:0;

               padding:20px;
                 height: 450px;
                overflow-y: scroll;
                overflow-x: hidden;
            }
      </style>
    <title>Messaging Center</title>


    <link rel="stylesheet" href="{% static "inbox/css/reset.css" %}">

        <link rel="stylesheet" href="{% static "inbox/css/style.css" %}">
              <link rel="stylesheet" href={% static "inbox/scss/style.scss"%}"">

  </head>

  <body>

    <div class="wrapper">
    <div class="container">
        <div id ="left" class="left">
            <div class="top">
                <center>Messaging Center</center>
{#                <img src="XL" alt=""/>#}
            </div>
            <ul id="people" class="people">
            </ul>
        </div>
        <div id ="right" class="right">
        </div>
    </div>
</div>

    <script src="{% static 'inbox/js/test.js'%}"></script>

    <script src="{% static "inbox/js/index.js"%}"></script>
    <script>
         function messlist() {
                info= {{allItems0 |safe}};
                appendToInnerHtml=[];
             for (i = 0; i<info.length; i += 1) {

                 appendToInnerHtml[i]=
                         '<li name='+i+' class="person" data-chat= person'+i+' onclick="messages('+i+')">'+


                        '<span class="name">'+info[i][2]+'</span>'+
                        '<br>'+
                        '<span class="preview">'+info[i][1]+'</span>' +

                         '</li>';

             }
             document.getElementById("people").innerHTML = appendToInnerHtml.join("");

         }
         messlist();
                function messages(i) {
                    info0= {{messages0 |safe}};

                    mess =[];
                    for (j = 0; j<info0[i].length; j += 1) {
                        mess[j]='<div id=person'+i+' class=person'+i+'><br>'+'<div class="conversation-start">'+
                                '<span>'+info0[i][j][0]+'<br>'+info0[i][j][1].split(':')[0]+':'+info0[i][j][1].split(':')[1]+'</span>'+
                            '</div>'+
                            '<div class="bubble you">'+
                                info0[i][j][2]+
                           '</div>'+'<br>'+'<br></div>';
                    }
                         document.getElementById("right").innerHTML =mess.join("")+
                           '<div id="reply" > <input class= "entTXT" type="text" id='+i+' name="reply" placeholder="Your message..">'+
                            '<input class="send" type="submit" value="Send" onclick="send('+i+')"/></div>';



                }
            messages(0);

         function send(x) {
             var reply = document.getElementById(x).value;
             var element = document.createElement("div");
             element.className = 'bubble you';
             element.appendChild(document.createTextNode(
                                reply
                          ));
             document.getElementById('person'+x).appendChild(element);
             document.getElementById(x).value=''
        }



    </script>




  </body>
</html>

templates/bootstrap-shop/inbox_.html
{% load static %}
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
       <link id="callCss" rel="stylesheet" href="{% static "themes/bootshop/bootstrap.min.css"%} " media="screen"/>
    <link href="{% static "themes/css/base.css" %}" rel="stylesheet" media="screen"/>
<!-- Bootstrap style responsive -->
	<link href="{% static "themes/css/bootstrap-responsive.min.css"%} "  rel="stylesheet"/>
	<link href="{% static "themes/css/font-awesome.css"%}" rel="stylesheet"  type="text/css">
<!-- Google-code-prettify -->
	<link href="{% static "themes/js/google-code-prettify/prettify.css"%} " rel="stylesheet"/>
<!-- fav and touch icons -->
    <link rel="shortcut icon" href="{% static "themes/images/L.png"%} ">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "themes/images/ico/apple-touch-icon-144-precomposed.png"%} " >
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "themes/images/ico/apple-touch-icon-114-precomposed.png"%} ">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "themes/images/ico/apple-touch-icon-72-precomposed.png"%} ">
    <link rel="apple-touch-icon-precomposed" href="{% static "themes/images/ico/apple-touch-icon-57-precomposed.png"%} ">
	<style type="text/css" id="enject">
    </style>
      <style>
.entTXT{
{#    position: absolute;#}
    bottom:0px;
    width: 100%;
    height:70px;
    padding: 12px 12px;
    margin: 18px 0;
    display: block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
</style>
      <style>
.send{
    float: right;
    font-size: 12px;
    font-weight:bold;
    width: 25%;
    height:15px;
    background-color: deepskyblue;
    color: white;
    padding: 25px 15px;
    margin: 4px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}
      </style>

        <style>
      .people
            {
                   left:0;
                   right:0;
                   top:60px;
                   padding:2px;
                 height: 500px;
                overflow-y: scroll;
                overflow-x: hidden;
            }
      </style>
      <style>
      .right

            {    left:0;
               right:0;

               padding:20px;
                 height: 450px;
                overflow-y: scroll;
                overflow-x: hidden;
            }
      </style>
    <title>Messaging Center</title>
    
    
       <link rel="stylesheet" href="{% static "inbox/css/reset.css" %}">

        <link rel="stylesheet" href="{% static "inbox/css/style.css" %}">
              <link rel="stylesheet" href={% static "inbox/scss/style.scss"%}"">


  </head>

  <body>
  <div class="navbar-inner">
    <a class="brand" href="http://127.0.0.1:8000"><img src="{% static "themes/images/minisamll1.png"%} " alt="Bootsshop"/></a>
{#		<form class="form-inline navbar-search" method="post" action="" enctype="multipart/form-data" >#}
{#                        			{% csrf_token %}#}
{##}
{#		<input  class="srchTxt" type="text" id="id_search" name="search" placeholder="what are you looking for.."  required />#}
{#		  <select class="srchTxt">#}
{#			<option>All</option>#}
{#			<option>CLOTHES </option>#}
{#			<option>FOOD AND BEVERAGES </option>#}
{#			<option>HEALTH & BEAUTY </option>#}
{#			<option>SPORTS & LEISURE </option>#}
{#			<option>BOOKS & ENTERTAINMENTS </option>#}
{#		</select>#}
{#		  <button type="submit" id="submitButton" class="btn btn-primary">Go</button>#}
{#    </form>#}
{#    <ul id="topMenu" class="nav pull-right">#}
{#  <!--  {% if user and not user.is_anonymous %} -->#}
{##}
{#	            <li class=""><a href="http://127.0.0.1:8000/select-item/">Sell with us</a></li>#}
{#         	 <li class=""><a href="http://127.0.0.1:8000/my-products/">My Products</a></li>#}
{#                  	 <li class=""><a href="http://127.0.0.1:8000/inbox/">Inbox</a></li>#}
{##}
{#             {% endif %}#}
{##}
{##}
{#	 <li class=""><a href="normal.html"></a></li>#}
{#	 <li class="">#}
{#          {% if user and not user.is_anonymous %}#}
{#      <li><a role="button"></a></li>#}
{##}
{#        <li><a role="button"  href="{% url 'auth:logout' %}?next={{ request.path}}" ><i class="fa fa-user w3-large"></i> <span class="btn btn-large btn-success">Log out</span></a></li>#}
{##}
{##}
{#    {% else %}#}
{#     <li ><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}" ><i class="fa fa-user w3-large"></i> <span class="btn btn-large btn-success">Login</span></a></li>#}
{##}
{#     {% endif %}#}
{##}
{#    </ul>#}
  </div>

	<script src="{% static "themes/js/jquery.js"%}" type="text/javascript"></script>
	<script src="{% static "themes/js/bootstrap.min.js"%}" type="text/javascript"></script>
	<script src="{% static "themes/js/google-code-prettify/prettify.js"%}"></script>

	<script src="{% static "themes/js/bootshop.js"%}"></script>
    <script src="{% static "themes/js/jquery.lightbox-0.5.js"%}"></script>

    <div class="wrapper">
    <div class="container">
        <div id ="left" class="left">
            <div class="top">
                <center>Messaging Center</center>
                </div>
            <ul id="people" class="people">
            </ul>
        </div>
        <div id ="right" class="right">
        </div>
    </div>
</div>

  <script src="{% static 'inbox/js/test.js'%}"></script>

    <script src="{% static "inbox/js/index.js"%}"></script>
    <script>
        product_type={{  type_of_|safe}};

         function messlist() {
                info= {{allItems0 |safe}};
                appendToInnerHtml=[];
             for (i = 0; i<info.length; i += 1) {

                 appendToInnerHtml[i]=
                         '<li name='+i+' class="person" data-chat= person'+i+' onclick="messages('+i+')">'+

                        '<span class="name">'+product_type[i][0][0]+'</span>'+
                        '<br>'+
                        '<span class="preview">'+info[i][1]+'</span>' +
                         '</li>';

             }
             document.getElementById("people").innerHTML = appendToInnerHtml.join("");

         }
         messlist();
                function messages(i) {
                    info0= {{messages0 |safe}};

                    mess =[];
                    for (j = 0; j<info0[i].length; j += 1) {
                        mess[j]='<div id=person'+i+' class=person'+i+'><br>'+'<div class="conversation-start">'+
                                '<span>'+info0[i][j][0]+'<br>'+info0[i][j][1].split(':')[0]+':'+info0[i][j][1].split(':')[1]+'</span>'+
                            '</div>'+
                            '<div class="bubble you">'+
                                info0[i][j][2]+
                           '</div>'+'<br>'+'<br></div>';
                    }
                         document.getElementById("right").innerHTML =mess.join("")+
                           '<div id="reply" > <input class= "entTXT" type="text" id='+i+' name="reply" placeholder="Your message..">'+
                            '<input class="send" type="submit" value="Send" onclick="send('+i+')"/></div>';



                }
            messages(0);



         function send(x) {
             var reply = document.getElementById(x).value;
             if (reply!==''){
                 var element = document.createElement("div");
             element.className = 'bubble you';
             element.appendChild(document.createTextNode(
                                reply
                          ));
             document.getElementById('person'+x).appendChild(element);
             document.getElementById(x).value='';


             }

        }



    </script>
  	<script src="{% static "themes/js/jquery.js"%}" type="text/javascript"></script>
	<script src="{% static "themes/js/bootstrap.min.js"%}" type="text/javascript"></script>
	<script src="{% static "themes/js/google-code-prettify/prettify.js"%}"></script>

	<script src="{% static "themes/js/bootshop.js"%}"></script>
    <script src="{% static "themes/js/jquery.lightbox-0.5.js"%}"></script>

    
    
    
  </body>
</html>

templates/bootstrap-shop/index_test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootshop online Shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
<!--Less styles -->
   <!-- Other Less css file //different less files has different color scheam
	<link rel="stylesheet/less" type="text/css" href="themes/less/simplex.less">
	<link rel="stylesheet/less" type="text/css" href="themes/less/classified.less">
	<link rel="stylesheet/less" type="text/css" href="themes/less/amelia.less">  MOVE DOWN TO activate
	-->
	<!--<link rel="stylesheet/less" type="text/css" href="themes/less/bootshop.less">
	<script src="themes/js/less.js" type="text/javascript"></script> -->
<!-- Bootstrap style -->
    <link id="callCss" rel="stylesheet" href="{% static "themes/bootshop/bootstrap.min.css"%} " media="screen"/>
    <link href="{% static "themes/css/base.css" %}" rel="stylesheet" media="screen"/>
<!-- Bootstrap style responsive -->
	<link href="{% static "themes/css/bootstrap-responsive.min.css"%} "  rel="stylesheet"/>
	<link href="{% static "themes/css/font-awesome.css"%}" rel="stylesheet"  type="text/css">
<!-- Google-code-prettify -->	
	<link href="{% static "themes/js/google-code-prettify/prettify.css"%} " rel="stylesheet"/>
<!-- fav and touch icons -->
    <link rel="shortcut icon" href="{% static "themes/images/minisamll1.png"%} ">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "themes/images/ico/apple-touch-icon-144-precomposed.png"%} " >
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "themes/images/ico/apple-touch-icon-114-precomposed.png"%} ">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "themes/images/ico/apple-touch-icon-72-precomposed.png"%} ">
    <link rel="apple-touch-icon-precomposed" href="{% static "themes/images/ico/apple-touch-icon-57-precomposed.png"%} ">
	<style type="text/css" id="enject">



    </style>
  </head>
<body>
<div id="header">
<div class="container">
<div id="welcomeLine" class="row">
	<div class="span6">Welcome!<strong> {{ user.get_full_name|default:user.username }}</strong></div>
	<div class="span6">
	<div class="pull-right">
	</div>
	</div>
</div>
<!-- Navbar ================================================== -->
<div id="logoArea" class="navbar">
<a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</a>
  <div class="navbar-inner">
    <a class="brand" href="index.html"><img src="{% static "themes/images/minisamll1.png"%} " alt="Bootsshop"/></a>
		<form class="form-inline navbar-search" method="post" action="" enctype="multipart/form-data" >
                        			{% csrf_token %}

		<input  class="srchTxt" type="text" id="id_search" name="search" placeholder="what are you looking for.."  required />
		  <select class="srchTxt">
			<option>All</option>
			<option>CLOTHES </option>
			<option>FOOD AND BEVERAGES </option>
			<option>HEALTH & BEAUTY </option>
			<option>SPORTS & LEISURE </option>
			<option>BOOKS & ENTERTAINMENTS </option>
		</select>
		  <button type="submit" id="submitButton" class="btn btn-primary">Go</button>
    </form>
    <ul id="topMenu" class="nav pull-right">
     {% if user and not user.is_anonymous %}

	            <li class=""><a href="http://127.0.0.1:8000/select-item/">Sell with us</a></li>
         	 <li class=""><a href="http://127.0.0.1:8000/my-products/">My Products</a></li>
                  	 <li class=""><a href="http://127.0.0.1:8000/inbox/">Inbox</a></li>

             {% endif %}


	 <li class=""><a href="normal.html"></a></li>
	 <li class="">
          {% if user and not user.is_anonymous %}
      <li><a role="button"></a></li>

        <li><a role="button"  href="{% url 'auth:logout' %}?next={{ request.path}}" ><i class="fa fa-user w3-large"></i> <span class="btn btn-large btn-success">Log out</span></a></li>


    {% else %}
     <li ><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}" ><i class="fa fa-user w3-large"></i> <span class="btn btn-large btn-success">Login</span></a></li>

     {% endif %}

    </ul>
  </div>
</div>
</div>
</div>
<!-- Header End====================================================================== -->
<div id="carouselBlk">
	<div id="myCarousel" class="carousel slide">
		<div class="carousel-inner">
		  <div class="item active">

		  </div>
		  <div class="item">

		  </div>
		  <div class="item">

		  </div>
		   <div class="item">

		  </div>
		   <div class="item">

		  </div>
		   <div class="item">

		  </div>
		</div>
		<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
	  </div> 
</div>
<div id="mainBody">
	<div class="container">
	<div class="row">
<!-- Sidebar ================================================== -->
	<div id="sidebar" class="span3">
		<ul id="sideManu" class="nav nav-tabs nav-stacked">
			<li class="subMenu open"><a> ELECTRONICS</a>
				<ul>
				<li><a class="active" href="http://127.0.0.1:8000/filtering"><i class="icon-chevron-right"></i>Cameras  </a></li>
				<li><a href="http://127.0.0.1:8000/devices"><i class="icon-chevron-right"></i>Computers, Tablets & laptop</a></li>
				<li><a href="http://127.0.0.1:8000/Accessories">><i class="icon-chevron-right"></i>Accessories</a></li>
				</ul>
			</li>
			<li class="subMenu"><a> CLOTHES  </a>
			<ul style="display:none">
				<li><a href="http://127.0.0.1:8000/notfound"><i class="icon-chevron-right"></i>Women's Clothing </a></li>
				<li><a href="http://127.0.0.1:8000/notfound"><i class="icon-chevron-right"></i>Women's Shoes </a></li>
				<li><a href="http://127.0.0.1:8000/notfound"><i class="icon-chevron-right"></i>Women's Hand Bags </a></li>
				<li><a href="http://127.0.0.1:8000/notfound"><i class="icon-chevron-right"></i>Men's Clothings  </a></li>
				<li><a href="http://127.0.0.1:8000/notfound"><i class="icon-chevron-right"></i>Men's Shoes </a></li>
				<li><a href="http://127.0.0.1:8000/notfound"><i class="icon-chevron-right"></i>Kids Clothing </a></li>
				<li><a href="http://127.0.0.1:8000/notfound"><i class="icon-chevron-right"></i>Kids Shoes </a></li>
			</ul>
			</li>
			<li class="subMenu"><a>Scholarship</a>
				<ul style="display:none">
				<li><a href="http://127.0.0.1:8000/scholarship"><i class="icon-chevron-right"></i>Scholarship</a></li>

			</ul>
			</li>
			<li><a href="http://127.0.0.1:8000/Books">BOOKS & ENTERTAINMENTS</a></li>
		</ul>


	</div>
<!-- Sidebar end=============================================== -->

		<div class="span9">		
			<div class="well well-small">
			<h4>Recent Posts<small class="pull-right">200+ featured products</small></h4>
			<div class="row-fluid">
			<div id="featured" class="carousel slide">
			<div class="carousel-inner">
			  <div class="item active">
			  <ul id='lastposts' class="thumbnails">

			  </ul>
			  </div>
			  </div>
			  <a class="left carousel-control" href="#featured" data-slide="prev">‹</a>
			  <a class="right carousel-control" href="#featured" data-slide="next">›</a>
			  </div>
			  </div>
		</div>


        <div id="recommendation">
             {% if user and not user.is_anonymous %}

		<h4>Recommended Items </h4>

            <div id="reco">

            </div>
            {% endif %}

		</div>
		</div>
	</div>
</div>
</div>
<!-- Footer ================================================================== -->
	<div  id="footerSection">
	<div class="container">
		<div class="row">
			<div class="span3">
				<h5>Istanbul Şehir University Online Market</h5>
				<a href="login.html">Istanbul - Turkey</a>
			 </div>
		 </div>
		<p class="pull-right">&copy; Şehir Online Market</p>
	</div><!-- Container End -->
	</div>
<!-- Placed at the end of the document so the pages load faster ============================================= -->
	<script src="{% static "themes/js/jquery.js"%}" type="text/javascript"></script>
	<script src="{% static "themes/js/bootstrap.min.js"%}" type="text/javascript"></script>
	<script src="{% static "themes/js/google-code-prettify/prettify.js"%}"></script>
	
	<script src="{% static "themes/js/bootshop.js"%}"></script>
    <script src="{% static "themes/js/jquery.lightbox-0.5.js"%}"></script>
	
	<!-- Themes switcher section ============================================================================================= -->
</body>
<script>


                info= {{convert_data |safe}};
                photo= {{convert_image |safe}};
                appendToInnerHtml=[];
             for (i = 0; i<info.length; i += 1) {

                 appendToInnerHtml[i]=
             '<ul class="thumbnails">'+
				'<li class="span3">'+
				  '<div class="thumbnail">'+
					'<a  href="http://127.0.0.1:8000/products/user/'+info[i][0]+'"><img src="http://127.0.0.1:8000/'+photo[i][1]+'" alt=""/></a>'+
					'<div class="caption">'+
					  '<h5>'
             +info[i][1]+'</h5>'+
					  '<p>'+
                      info[i][2]+
					  '</p>'+
					  '<h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn"  href="http://127.0.0.1:8000/products/user/'+info[i][0]+'">show <i class="icon-shopping-cart"></i></a></h4>'+
					'</div>'+
				  '</div>'+
				'</li>'+
			  '</ul>';

             }
             document.getElementById("reco").innerHTML = appendToInnerHtml.join("");

</script>
<script>
    lastposts=[];
    appendToInnerHt=[];
    recent_post= {{s1 |safe}};



    recent_images={{s2 |safe}};



    for (i=0; i<recent_post.length;i+=1){
        appendToInnerHt[i]= '<li class="span3">'+
				  '<div class="thumbnail">'+
				  '<i class="tag">'+'</i>'+


					'<a href="http://127.0.0.1:8000/products/user/'+recent_images[i][0]+'"><img src="http://127.0.0.1:8000/'+recent_images[i][1]+'" alt=""></a>'+
					'<div class="caption">'+
					 ' <h5>'+recent_post[i][1]+'</h5>'+
					  '<h4>'+recent_post[i][2]+'</span></h4>'+
					'</div>'+
				  '</div>'+
				'</li>';

    }
                 document.getElementById("lastposts").innerHTML = appendToInnerHt.join('')
</script>
</html>